sonar.projectKey=cd09ae26ff4d23cf5d6d242369976139f0c48e8c
sonar.working.directory=C:\\Users\\adriana\\Documents\\UPT\\2026II\\calidadYPruebasDeSoftware\\bank\\.sonarqube\\out\\.sonar
sonar.projectBaseDir=C:\\Users\\adriana\\Documents\\UPT\\2026II\\calidadYPruebasDeSoftware\\bank
sonar.pullrequest.cache.basepath=C:\\Users\\adriana\\Documents\\UPT\\2026II\\calidadYPruebasDeSoftware\\bank
sonar.sources=\
"C:\\Users\\adriana\\Documents\\UPT\\2026II\\calidadYPruebasDeSoftware\\bank\\.github\\workflows\\release.yml",\
"C:\\Users\\adriana\\Documents\\UPT\\2026II\\calidadYPruebasDeSoftware\\bank\\.github\\workflows\\sonar.yml"

B6D2A745-4C76-41D9-A62D-E37BDF189D91.sonar.projectKey=cd09ae26ff4d23cf5d6d242369976139f0c48e8c:B6D2A745-4C76-41D9-A62D-E37BDF189D91
B6D2A745-4C76-41D9-A62D-E37BDF189D91.sonar.projectName=Bank.Domain
B6D2A745-4C76-41D9-A62D-E37BDF189D91.sonar.projectBaseDir=C:\\Users\\adriana\\Documents\\UPT\\2026II\\calidadYPruebasDeSoftware\\bank\\Bank.Domain
B6D2A745-4C76-41D9-A62D-E37BDF189D91.sonar.sourceEncoding=utf-8
B6D2A745-4C76-41D9-A62D-E37BDF189D91.sonar.tests=
B6D2A745-4C76-41D9-A62D-E37BDF189D91.sonar.sources=\
"C:\\Users\\adriana\\Documents\\UPT\\2026II\\calidadYPruebasDeSoftware\\bank\\Bank.Domain\\Models\\BankAccount.cs",\
"C:\\Users\\adriana\\Documents\\UPT\\2026II\\calidadYPruebasDeSoftware\\bank\\Bank.Domain\\obj\\Bank.Domain.csproj.nuget.dgspec.json",\
"C:\\Users\\adriana\\Documents\\UPT\\2026II\\calidadYPruebasDeSoftware\\bank\\Bank.Domain\\obj\\project.assets.json",\
"C:\\Users\\adriana\\Documents\\UPT\\2026II\\calidadYPruebasDeSoftware\\bank\\Bank.Domain\\bin\\Debug\\net9.0\\Bank.Domain.deps.json",\
"C:\\Users\\adriana\\Documents\\UPT\\2026II\\calidadYPruebasDeSoftware\\bank\\Bank.Domain\\bin\\Release\\net9.0\\Bank.Domain.deps.json",\
"C:\\Users\\adriana\\Documents\\UPT\\2026II\\calidadYPruebasDeSoftware\\bank\\Bank.Domain\\obj\\Debug\\net9.0\\Bank.Domain.sourcelink.json",\
"C:\\Users\\adriana\\Documents\\UPT\\2026II\\calidadYPruebasDeSoftware\\bank\\Bank.Domain\\obj\\Release\\net9.0\\Bank.Domain.sourcelink.json"

B6D2A745-4C76-41D9-A62D-E37BDF189D91.sonar.cs.analyzer.projectOutPaths=\
"C:\\Users\\adriana\\Documents\\UPT\\2026II\\calidadYPruebasDeSoftware\\bank\\.sonarqube\\out\\0"
B6D2A745-4C76-41D9-A62D-E37BDF189D91.sonar.cs.roslyn.reportFilePaths=\
"C:\\Users\\adriana\\Documents\\UPT\\2026II\\calidadYPruebasDeSoftware\\bank\\.sonarqube\\out\\0\\Issues.json"
B6D2A745-4C76-41D9-A62D-E37BDF189D91.sonar.cs.scanner.telemetry=\
"C:\\Users\\adriana\\Documents\\UPT\\2026II\\calidadYPruebasDeSoftware\\bank\\.sonarqube\\out\\0\\Telemetry.json"

B6D2A745-4C76-41D9-A62D-E37BDF189D91.sonar.working.directory=C:\\Users\\adriana\\Documents\\UPT\\2026II\\calidadYPruebasDeSoftware\\bank\\.sonarqube\\out\\.sonar\\mod0
DE5673BA-9692-4211-B3A5-DAE2ED4CD964.sonar.projectKey=cd09ae26ff4d23cf5d6d242369976139f0c48e8c:DE5673BA-9692-4211-B3A5-DAE2ED4CD964
DE5673BA-9692-4211-B3A5-DAE2ED4CD964.sonar.projectName=Bank.Domain.Tests
DE5673BA-9692-4211-B3A5-DAE2ED4CD964.sonar.projectBaseDir=C:\\Users\\adriana\\Documents\\UPT\\2026II\\calidadYPruebasDeSoftware\\bank\\Bank.Domain.Tests
DE5673BA-9692-4211-B3A5-DAE2ED4CD964.sonar.sourceEncoding=utf-8
DE5673BA-9692-4211-B3A5-DAE2ED4CD964.sonar.sources=
DE5673BA-9692-4211-B3A5-DAE2ED4CD964.sonar.tests=\
"C:\\Users\\adriana\\Documents\\UPT\\2026II\\calidadYPruebasDeSoftware\\bank\\Bank.Domain.Tests\\obj\\Bank.Domain.Tests.csproj.nuget.dgspec.json",\
"C:\\Users\\adriana\\Documents\\UPT\\2026II\\calidadYPruebasDeSoftware\\bank\\Bank.Domain.Tests\\obj\\project.assets.json",\
"C:\\Users\\adriana\\Documents\\UPT\\2026II\\calidadYPruebasDeSoftware\\bank\\Bank.Domain.Tests\\bin\\Debug\\net9.0\\Bank.Domain.Tests.deps.json",\
"C:\\Users\\adriana\\Documents\\UPT\\2026II\\calidadYPruebasDeSoftware\\bank\\Bank.Domain.Tests\\bin\\Debug\\net9.0\\Bank.Domain.Tests.runtimeconfig.json",\
"C:\\Users\\adriana\\Documents\\UPT\\2026II\\calidadYPruebasDeSoftware\\bank\\Bank.Domain.Tests\\obj\\Debug\\net9.0\\Bank.Domain.Tests.sourcelink.json",\
"C:\\Users\\adriana\\Documents\\UPT\\2026II\\calidadYPruebasDeSoftware\\bank\\Bank.Domain.Tests\\BankAccountTests.cs",\
"C:\\Users\\adriana\\Documents\\UPT\\2026II\\calidadYPruebasDeSoftware\\bank\\Bank.Domain.Tests\\TestResults\\7aaf44f0-58f4-4046-b62b-b8abfe195450\\coverage.opencover.xml",\
"C:\\Users\\adriana\\Documents\\UPT\\2026II\\calidadYPruebasDeSoftware\\bank\\Bank.Domain.Tests\\TestResults\\f837e41e-9f2e-4b4a-8376-811a13619991\\coverage.opencover.xml"

DE5673BA-9692-4211-B3A5-DAE2ED4CD964.sonar.cs.analyzer.projectOutPaths=\
"C:\\Users\\adriana\\Documents\\UPT\\2026II\\calidadYPruebasDeSoftware\\bank\\.sonarqube\\out\\1"
DE5673BA-9692-4211-B3A5-DAE2ED4CD964.sonar.cs.roslyn.reportFilePaths=\
"C:\\Users\\adriana\\Documents\\UPT\\2026II\\calidadYPruebasDeSoftware\\bank\\.sonarqube\\out\\1\\Issues.json"
DE5673BA-9692-4211-B3A5-DAE2ED4CD964.sonar.cs.scanner.telemetry=\
"C:\\Users\\adriana\\Documents\\UPT\\2026II\\calidadYPruebasDeSoftware\\bank\\.sonarqube\\out\\1\\Telemetry.json"

DE5673BA-9692-4211-B3A5-DAE2ED4CD964.sonar.working.directory=C:\\Users\\adriana\\Documents\\UPT\\2026II\\calidadYPruebasDeSoftware\\bank\\.sonarqube\\out\\.sonar\\mod1
sonar.organization=laos19
sonar.visualstudio.enable=false
sonar.host.url=https://sonarcloud.io

sonar.modules=B6D2A745-4C76-41D9-A62D-E37BDF189D91,DE5673BA-9692-4211-B3A5-DAE2ED4CD964

